name       : ffmpegthumbs
version    : 21.04.3
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/ffmpegthumbs-21.04.3.tar.xz : b5a7652525cddf1d9a19f3016b026950e95d6d1269cf4f77cff051cf5fbc4653
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
optimize   : lto
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(taglib)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
