name       : ffmpegthumbs
version    : 18.04.3
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/ffmpegthumbs-18.04.3.tar.xz : e6b2e6cd096bbc87696fbdecec0c21de3ee688161fa0b1adc83952a8f8004472
license    : GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
