name       : ffmpegthumbs
version    : 23.04.1
release    : 65
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/ffmpegthumbs-23.04.1.tar.xz : d82573a0993b68406e57e28395d59dd719fca0fb20af383df0af34245a45ea2f
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
optimize   : lto
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(taglib)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
