name       : ffmpegthumbs
version    : 22.04.2
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/ffmpegthumbs-22.04.2.tar.xz : e46b30ba98b16a6307d03ad03b5801fb745630b4b14734ab2574043bcd54645d
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
optimize   : lto
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(taglib)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
