name       : ffmpegthumbs
version    : 21.08.2
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/ffmpegthumbs-21.08.2.tar.xz : e117df20f05830514e5b8dc6994420b4fc449212a3cc1d0b2279606550655dbf
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
optimize   : lto
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(taglib)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
