name       : ffmpegthumbs
version    : 17.12.0
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.0/src/ffmpegthumbs-17.12.0.tar.xz : 04115ddafbffee3bff9dfa8b39ca7f9b107ae18e908d09dcaaf54bb633b60204
license    : GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
