name       : ffmpegthumbs
version    : 21.08.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/ffmpegthumbs-21.08.0.tar.xz : b5b8f70cd63b08a5d83b8bc18c0fa516341f7d498a5fb1d98b77c5eeb6b37131
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
optimize   : lto
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(taglib)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
