name       : ffmpegthumbs
version    : 18.08.1
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/ffmpegthumbs-18.08.1.tar.xz : 6cc219f28d38e10f18d8d75d048180d59c50b7eb5812a0ca27b199ea06cffc85
license    : GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
