name       : ffmpegthumbs
version    : 17.08.2
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/ffmpegthumbs-17.08.2.tar.xz : d0c6f3b2adbbbdb76540b010c94dc573fda2eaa62a65174450205b094c6ecc2f
license    : GPL-2.0
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
