name       : ffmpegthumbs
version    : 21.12.3
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/ffmpegthumbs-21.12.3.tar.xz : 9a9b310eef45990f065449688801f435fbc9e0a936c83e6e307f7e0546bf4f74
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
optimize   : lto
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(taglib)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
