name       : ffmpegthumbs
version    : 17.12.3
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/ffmpegthumbs-17.12.3.tar.xz : 25c68b230004579a3c97654baaedb63796a1b9334d7ede512ac4e5ee56f7c2a1
license    : GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
