name       : ffmpegthumbs
version    : 17.12.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/ffmpegthumbs-17.12.1.tar.xz : 5a706e634367320bbf6d43ac937453baed0917fa98838158c9d84275d545ad52
license    : GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
