name       : ffmpegthumbs
version    : 22.04.1
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/ffmpegthumbs-22.04.1.tar.xz : 8c2f7bdccde8f6ee78f8c6fe77cd6d0558fcc0173fb6605f04fddf453c9d7875
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
optimize   : lto
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(taglib)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
