name       : ffmpegthumbs
version    : 17.12.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/ffmpegthumbs-17.12.2.tar.xz : c2d54af7adc83432c9415526b2ac032d2400280fefc6d5634c7862b9a1301c25
license    : GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
