name       : ffmpegthumbs
version    : 20.04.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/ffmpegthumbs-20.04.2.tar.xz : 24d5fd77abc5481318dd9b301badc9175dcd1ceb15801b4576ab9b4223019aff
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
