name       : ffmpegthumbs
version    : 19.04.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/ffmpegthumbs-19.04.0.tar.xz : 6b96cea0c142651cb586eb40d88792329f8da9a777d9a457ba76d0e94ddf4995
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
