name       : ffmpegthumbs
version    : 20.12.2
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/ffmpegthumbs-20.12.2.tar.xz : 6f69dc7bdc45f5ad76c008cc160bd8799c3239f25c6eaea2ad6bca30fa798147
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
optimize   : lto
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(taglib)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
