name       : ffmpegthumbs
version    : 18.04.1
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/ffmpegthumbs-18.04.1.tar.xz : d662902d84af794fb565f50f7c464f8b184e38096a0db60e23cceed779189a1a
license    : GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
