name       : ffmpegthumbs
version    : 20.12.1
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/ffmpegthumbs-20.12.1.tar.xz : afb0a47751cee3c9e7ccfa8504076bbdd03665afa92f38dd842b2aed3ceee99e
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
optimize   : lto
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(taglib)
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
