name       : ffmpegthumbs
version    : 20.08.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/ffmpegthumbs-20.08.0.tar.xz : 84c3a8f064423d7e51a57b9ed32a9f4fdbca73f7fa7e47a6289d9b516f1ba9ff
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
